server:
  port: 10080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user
    client:
      grant-type: client_credentials

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.vinapex: DEBUG

spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination:  orgChangeTopic
          content-type: application/json
          group: licensingGroup
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092